name: dev-release

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    name: Build and upload to Test PyPi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build & Publish
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
      run: |
        python version.py
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*
