name: macos

on: [push, pull_request]

jobs:
  MacOS:
    name: MacOS - ${{ matrix.PYTHON_VERSION }} - ${{ matrix.ICONIFY_QTLIB }}
    runs-on: macos-latest
    env:
      ICONIFY_QTLIB: ${{ matrix.ICONIFY_QTLIB }}
    strategy:
      fail-fast: False
      matrix:
        ICONIFY_QTLIB: ['PySide2', 'Qt', 'qtpy']
        PYTHON_VERSION: ['py2', 'py3']
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install Dependencies
        run: pip install tox
      - name: Run Tests
        run: tox -e ${{ matrix.PYTHON_VERSION }}
