name: CI

on: [push]

jobs:
  test-ubuntu:

    runs-on: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install System Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libegl1-mesa
    - name: Setup Python
      uses: actions/setup-python@v1
    - name: Install Tox
      run: pip install tox
    - name: Run Tox
      shell: bash -l {0}
      run: xvfb-run --auto-servernum tox
