name: CI

on: [push]

jobs:
  test-ubuntu:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install System Packages
      run: |
        sudo apt-get update
        sudo apt-get install libegl1-mesa
    - name: Setup Python
      uses: actions/setup-python@v1
    - name: Install Tox and any other packages
      run: pip install tox
    - name: Run Tests
      shell: bash -l {0}
      run: xvfb-run --auto-servernum tox
