name: windows

on: [push, pull_request]

jobs:
  Windows:
    name: Windows - py3 - ${{ matrix.ICONIFY_QTLIB }}
    runs-on: windows-latest
    env:
      ICONIFY_QTLIB: ${{ matrix.ICONIFY_QTLIB }}
    strategy:
      fail-fast: False
      matrix:
        ICONIFY_QTLIB: ['PySide2', 'Qt', 'qtpy']
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install Dependencies
        run: pip install tox
      - name: Run Tests
        run: tox -e py3
